RolêTopMVC/ViewModels/PacoteViewModel.cs
using RolêTopMVC.Enums;
using RolêTopMVC.Models;

namespace RolêTopMVC.ViewModels
{
    public class PacoteViewModel : AgendamentoViewModel
    {
        public int CodigoPacoteSimples {get;set;}
        public int CodigoPacotePadrao {get;set;}
        public int CodigoPacotePremium {get;set;}

        public PacoteViewModel()
        {
            this.CodigoPacotePadrao = (int) ValorPacotes.PacotePadrao;
            this.CodigoPacoteSimples = (int) ValorPacotes.PacoteSimples;
            this.CodigoPacotePremium = (int) ValorPacotes.PacotePremium;
        }

    }
}

RolêTopMVC/Controllers/PacoteController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RolêTopMVC.Models;
using RolêTopMVC.ViewModels;

namespace RolêTopMVC.Controllers
{
    public class PacoteController : AbstractController
    {
        public IActionResult Index(PacoteViewModel pacoteViewModel)
        {
            pacoteViewModel.NomeView = "Pacote";
            return View(pacoteViewModel);
        }

        

    }
}

RolêTopMVC/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RolêTopMVC.Enums;
using RolêTopMVC.Models;
using RolêTopMVC.Repositorio;
using RolêTopMVC.ViewModels;
using static RolêTopMVC.ViewModels.PedidoViewModel;

namespace RolêTopMVC.Controllers
{

    public class PedidoController : AbstractController
    {
        ProdutoRepository produtoRepository = new ProdutoRepository();
        ClienteRepository clienteRepository = new ClienteRepository();
    
        public IActionResult Registrar(int id)
        {
            AgendamentoViewModel avm= new AgendamentoViewModel();

            // switch (id)
            // {
            //     case (int) ValorPacotes.PacoteSimples:
            //         avm.NomeView = "Simples";
            //         PacoteSimples ps = new PacoteSimples();
            //         avm.PacoteSimples = ps;
            //         break;
            //     case (int) ValorPacotes.PacotePadrao:
            //         avm.NomeView = "Padrao";
            //         PacotePadrao pp = new PacotePadrao();
            //         avm.PacotePadrao = pp;
            //         break;
            //     case (int )ValorPacotes.PacotePremium:
            //         avm.NomeView = "Premium";
            //         PacotePremium prep = new PacotePremium();
            //         avm.PacotePremium = prep;
            //         break;
            // }

            avm.CodigoPacote = id;
            return RedirectToAction("Index","Agendamento", avm);
        }


        public IActionResult Aprovar (ulong id)
        {
            var pedido = produtoRepository.ObterPor(id);

            if(produtoRepository.Atualizar(pedido))
            {
                return RedirectToAction("Dashboard", "Administrador");
            }
            else
            {
                return View("Erro", new RespostasViewModel("Não foi possível aprovar este pedido")
                {
                    NomeView = "Dashdoard",
                    UsuarioEmail = ObterUsuarioSession(),
                    UsuarioNome = ObterUsuarioNomeSession()
                });
            }
        }

                public IActionResult Reprovar (ulong id)
        {
            var pedido = produtoRepository.ObterPor(id);

            if(produtoRepository.Atualizar(pedido))
            {
                return RedirectToAction("Dashboard", "Administrador");
            }
            else
            {
                return View("Erro", new RespostasViewModel("Não foi possível reprovar este pedido")
                {
                    NomeView = "Dashdoard",
                    UsuarioEmail = ObterUsuarioSession(),
                    UsuarioNome = ObterUsuarioNomeSession()
                });
            }
        }
    }
}

RolêTopMVC/Views/Pacote/Index.cshtml
@model RolêTopMVC.ViewModels.PacoteViewModel
<main>
            <section id="tudo">
                <div>
                    <h1>Pacotes</h1>
                </div>
                    
                    <label class="tex" for="PacoteSimples"></div>
                        <p>   
                        <b><label class="tex" for="PacoteSimples" >Pacote Simples</label></b>
                        <input type="hidden" name="PacoteSimples" />
                        <br> 
                        <br>
                        <br>
                        <p>Alugar o espaço</p>
                        <br>
                        <br>
                        <br>
                        <p>Valor:10,000R$</p>
                        <br>
                        <br>
            <a href='@Url.Action("Registrar", "Pedido", new {id = @Model.CodigoPacoteSimples})' method="GET" class="pacotes">
                        <input type="submit" class="compra"><b>Compre já!</a></b></div> 
                        </p>
                    </div>
                    </a>
                    
                    <label class="tex" for="PacotePadrao"></div>
                        <p>
                        <b><label class="tex" for="PacotePadrao" >Pacote Padrao</label></b>
                        <input type="hidden" name="PacotePadrao"/>
                        <br>
                        <br>
                        <p>Alugar o espaço
                        <br>
                        mais o som
                        <br>
                        ou a luz.</p>
                        <br>
                        <br>
                        <p>Valor: 15,000R$</p>
                        <br>
                        <br>
                    <a href='@Url.Action("Registrar", "Pedido", new {id = @Model.CodigoPacotePadrao})' method="GET" class="pacotes">
                        <input type="submit" class="compra" ><b>Compre já!</a></b></div> 
                    </div>
                    </a>
        
                    <label class="tex" for="PacotePremium"></div>
                        <p>
                        <b><label class="tex" for="PacotePremium" >Pacote Premium</label></b>
                        <input type="hidden" name="PacotePremium"/>
                        <br>
                        <br>
                        <p>Alugar o espaço
                        <br>
                        mais o som
                        <br>
                        e a luz.</p>
                        <br>
                        <br>
                        <p>Valor: 20,000R$</p>
                        <br>
                        <br>
                    <a href='@Url.Action("Registrar", "Pedido", new {id = @Model.CodigoPacotePremium})' method="GET" class="pacotes">
                        <input type="submit" class="compra" ><b>Compre já!</a></b></div> 
                        </div> 
                        </a>
                    </div> 
                </div>
            </section>
            </main>

RolêTopMVC/Views/Pacote/pacote.cshtml
<main>
            <section id="tudo">
                <div>
                    <h1>Pacotes</h1>
                </div>
            
            <form action="" method="POST" class="pacotes">
                    <label class="tex" for="PacoteSimples"></div>
                        <p>   
                        <b><label class="tex" for="PacoteSimples" >Pacote Simples</label></b>
                        <input type="hidden" name="PacoteSimples" />
                        <br> 
                        <br>
                        <br>
                        <p>Alugar o espaço</p>
                        <br>
                        <br>
                        <br>
                        <p>Valor:10,000R$</p>
                        <br>
                        <br>
                        <input type="submit" class="compra" name="comprar"><b>Compre já!</a></b></div> 
                        </p>
                    </div>
                    </form>
                    
                    <form action="" method="POST" class="pacotes">
                    <label class="tex" for="PacotePadrao"></div>
                        <p>
                        <b><label class="tex" for="PacotePadrao" >Pacote Padrao</label></b>
                        <input type="hidden" name="PacotePadrao"/>
                        <br>
                        <br>
                        <p>Alugar o espaço
                        <br>
                        mais o som
                        <br>
                        ou a luz.</p>
                        <br>
                        <br>
                        <p>Valor: 15,000R$</p>
                        <br>
                        <br>
                        <input type="submit" class="compra" name="comprar"><b>Compre já!</a></b></div> 
                    </div>
                    </form>
        
                    <form action="" method="POST" class="pacotes">
                    <label class="tex" for="PacotePremium"></div>
                        <p>
                        <b><label class="tex" for="PacotePremium" >Pacote Premium</label></b>
                        <input type="hidden" name="PacotePremium"/>
                        <br>
                        <br>
                        <p>Alugar o espaço
                        <br>
                        mais o som
                        <br>
                        e a luz.</p>
                        <br>
                        <br>
                        <p>Valor: 20,000R$</p>
                        <br>
                        <br>
                        <input type="submit" class="compra" name="comprar"><b>Compre já!</a></b></div> 
                        </div> 
                        </form>
                    </div> 
                </div>
            </section>
            </main>